package Interfaces;

import Clases.Metodos_1;
import Conexiones.Conexion;
import Interfaces.Menu;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Andrea Martinez
 */
public class Asociaciones extends javax.swing.JFrame {
Metodos_1 con;
    /**
     * Creates new form Asociaciones
     */
    public Asociaciones() {
          con=new Metodos_1();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        idAsociaciones = new javax.swing.JTextField();
        NombreAsociaciones = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        EstatusAsociaciones = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        btnConsultar1 = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbAsociaciones = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Asociaciones ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 312, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("IdAsociacion ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 29));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 154, 79, 25));

        idAsociaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idAsociacionesKeyTyped(evt);
            }
        });
        getContentPane().add(idAsociaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 160, 30));

        NombreAsociaciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreAsociacionesKeyTyped(evt);
            }
        });
        getContentPane().add(NombreAsociaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 160, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Estatus ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 62, 26));
        getContentPane().add(EstatusAsociaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 90, 30));

        jButton1.setBackground(new java.awt.Color(0, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cancelar ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 110, 40));

        btnAgregar1.setBackground(new java.awt.Color(0, 204, 255));
        btnAgregar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregar1.setText("Agregar ");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 110, 40));

        btnConsultar1.setBackground(new java.awt.Color(0, 204, 255));
        btnConsultar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultar1.setText("Consultar ");
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 120, 40));

        btnActualizar1.setBackground(new java.awt.Color(0, 204, 255));
        btnActualizar1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizar1.setText("Actualizar ");
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 120, 40));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar ");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 100, 40));

        TbAsociaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdAsociacion", "Nombre ", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TbAsociaciones);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 97));

        btnSalir.setBackground(new java.awt.Color(0, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 60, 100, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
   Object datosAg[]= new Object[3];
        datosAg[0]=Integer.parseInt(idAsociaciones.getText());
        datosAg[1]=NombreAsociaciones.getText();
        datosAg[2]=EstatusAsociaciones.getText();
      
        con.insertarAsocion(datosAg);
        borraTabla(TbAsociaciones);
        this.repaint();
         idAsociaciones.setText(" ");
        NombreAsociaciones.setText(" ");
        EstatusAsociaciones.setText(" ");
    }//GEN-LAST:event_btnAgregar1ActionPerformed

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
        borraTabla(TbAsociaciones);
        con.consultaAsocion(TbAsociaciones);
        
        
        this.repaint();
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
    Object datosCon[]= new Object[4];
        datosCon[0]=Integer.parseInt(idAsociaciones.getText());
        datosCon[1]=NombreAsociaciones.getText();
        datosCon[2]=EstatusAsociaciones.getText();
        
        con.actualizaAsocion(datosCon);
        borraTabla(TbAsociaciones);
        
        this.repaint();
         idAsociaciones.setText(" ");
        NombreAsociaciones.setText(" ");
        EstatusAsociaciones.setText(" ");
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
           
                  
        int row= TbAsociaciones.getSelectedRow();
        int opt=JOptionPane.showConfirmDialog(this,"Estas seguro que desea eliminar este registro","Pregunta",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opt==JOptionPane.YES_OPTION){
           
            try {
                con.eliminarAsocion(Integer.valueOf(idAsociaciones.getText()));
              
                
            } catch (Exception ex) {
                
            }
                
            
        }else{}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   idAsociaciones.setText(" ");
        NombreAsociaciones.setText(" ");
        EstatusAsociaciones.setText(" ");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Menu menu= new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void idAsociacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idAsociacionesKeyTyped
        char c= evt.getKeyChar();
        if(c<'0'||c>'9')evt.consume();
    }//GEN-LAST:event_idAsociacionesKeyTyped

    private void NombreAsociacionesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreAsociacionesKeyTyped
        char c= evt.getKeyChar();
        if((c<'a'||c>'z') && c<'A' |c>'Z')evt.consume();
    }//GEN-LAST:event_NombreAsociacionesKeyTyped
  public void borraTabla(JTable tl){
        DefaultTableModel tablaTemp= (DefaultTableModel) tl.getModel();
        for (int i =tablaTemp.getRowCount()-1;i>=0; i--) {
            tablaTemp.removeRow(i);
            tablaTemp.removeTableModelListener(tl);
        }
       }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Asociaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Asociaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Asociaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Asociaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Asociaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EstatusAsociaciones;
    private javax.swing.JTextField NombreAsociaciones;
    private javax.swing.JTable TbAsociaciones;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField idAsociaciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
