package Interfaces;

import Clases.Metodos_1;
import Interfaces.Menu;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Antonio Cervantes
 */
public class Clientes extends javax.swing.JFrame {
Metodos_1 a=new Metodos_1(); 
    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }
public void borrarTabla() {
        try {
            DefaultTableModel tabT = (DefaultTableModel) tblClientes.getModel();
            for (int i = tabT.getRowCount() - 1; i > -1; i--) {
                tabT.removeRow(i);
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        idClientes = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();
        rSocial = new javax.swing.JTextField();
        limiteCredito = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        codigoPostal = new javax.swing.JTextField();
        RFC = new javax.swing.JTextField();
        telefono = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        idCiudad = new javax.swing.JTextField();
        cbtipo = new javax.swing.JComboBox();
        btnAgragar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("Clientes");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 180, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("IdCliente ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("RazonSocial");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 100, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("LimiteCredito");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 110, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Dirección ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Codigo Postal ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("RFC");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 60, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Telefono ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 90, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Email ");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 130, 60, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Tipo");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, 70, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("IdCiudad");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 80, 30));

        idClientes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idClientesKeyTyped(evt);
            }
        });
        getContentPane().add(idClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 140, 30));

        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        getContentPane().add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 140, 30));
        getContentPane().add(rSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 140, 30));
        getContentPane().add(limiteCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 140, 30));
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 210, 30));
        getContentPane().add(codigoPostal, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 120, 30));
        getContentPane().add(RFC, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 120, 30));
        getContentPane().add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 120, 30));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 190, 30));
        getContentPane().add(idCiudad, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 260, 150, 30));

        cbtipo.setBackground(new java.awt.Color(0, 204, 255));
        cbtipo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elija", "Mayoreo", "Menudeo" }));
        getContentPane().add(cbtipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 190, 160, 40));

        btnAgragar.setBackground(new java.awt.Color(0, 204, 255));
        btnAgragar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgragar.setText("Agregar ");
        btnAgragar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgragarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgragar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 110, 40));

        btnConsultar.setBackground(new java.awt.Color(0, 204, 255));
        btnConsultar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 110, 40));

        btnActualizar.setBackground(new java.awt.Color(0, 204, 255));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar ");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 120, 40));

        btnEliminar.setBackground(new java.awt.Color(0, 204, 255));
        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar ");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 390, 120, 40));

        btnCancelar.setBackground(new java.awt.Color(0, 204, 255));
        btnCancelar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelar.setText("Cancelar ");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, 110, 40));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdCliente", "Nombre ", "Razón Social", "Limite Credito ", "Dirección ", "Codigo Postal", "RFC", "Teléfono", "Email ", "Tipo ", "IdCiudad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 1040, 100));

        btnSalir.setBackground(new java.awt.Color(0, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 40, 100, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgragarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgragarActionPerformed
 try{
                Object datos[]={
                    Integer.parseInt(idClientes.getText()),
                    Nombre.getText(),
                    rSocial.getText(),
                    Integer.parseInt(limiteCredito.getText()),
                    Direccion.getText(),
                    Integer.valueOf(codigoPostal.getText()),
                    RFC.getText(),
                    Integer.parseInt(telefono.getText()),
                    Email.getText(),
                    cbtipo.getSelectedItem(),
                    Integer.parseInt(idCiudad.getText())
                    
                };
                a.insertaCliente(datos);
                idClientes.setText("");
                Nombre.setText("");
                rSocial.setText("");
                limiteCredito.setText("");
                Direccion.setText("");
                codigoPostal.setText("");
                RFC.setText("");
                telefono.setText("");
                Email.setText("");
                
                cbtipo.setSelectedItem(0);
                idCiudad.setText("");
            }catch(Exception e){
                idClientes.setText("");
                Nombre.setText("");
                rSocial.setText("");
                limiteCredito.setText("");
                Direccion.setText("");
                codigoPostal.setText("");
                RFC.setText("");
                telefono.setText("");
                Email.setText("");
                
                cbtipo.setSelectedItem(0);
                idCiudad.setText("");
            }
    }//GEN-LAST:event_btnAgragarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
          try {
            borrarTabla();
            a.consultaCliente(tblClientes);
        } catch (Exception e) {
            System.out.println("No hay registros"+ e);
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        Object datos [] = new Object[11];
            datos[0]=Integer.parseInt(idClientes.getText());
            datos[1]=Nombre.getText();
           datos[2]=rSocial.getText();
            datos[3]=Integer.parseInt(limiteCredito.getText());
            datos[4]=Direccion.getText();
            datos[5]=Integer.parseInt(codigoPostal.getText());
            datos[6]=RFC.getText();
            datos[7]=Integer.parseInt(telefono.getText());
            datos[8]=Email.getText();
            datos[9]=cbtipo.getSelectedItem();
            datos[10]=Integer.parseInt(idCiudad.getText());

            a.actualiza(datos);
            
            idClientes.setText("");
            Nombre.setText("");
            rSocial.setText("");
            limiteCredito.setText("");
            Direccion.setText("");
            codigoPostal.setText("");
            RFC.setText("");
            telefono.setText("");
            Email.setText("");    
            cbtipo.setSelectedItem(0);
            idCiudad.setText("");
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       int row= tblClientes.getSelectedRow();
        int opt=JOptionPane.showConfirmDialog(this,"estas seguro que desea eliminar este registro","Pregunta",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opt==JOptionPane.YES_OPTION){
           
         
            try {
                a.EliminarCliente(Integer.parseInt(idClientes.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                
              
        }else{JOptionPane.showMessageDialog(null, "no ha sido eliminado");}
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
     idClientes.setText("");
      Nombre.setText("");
      rSocial.setText("");
      limiteCredito.setText("");
      Direccion.setText("");
      codigoPostal.setText("");
      RFC.setText("");
      telefono.setText("");
      Email.setText("");    
      cbtipo.setSelectedItem(0);
      idCiudad.setText("");
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
     Menu menu= new Menu();
     menu.setVisible(true);
     menu.setLocationRelativeTo(null);
     this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void idClientesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idClientesKeyTyped
                char c= evt.getKeyChar();
        if(c<'0'||c>'9') evt.consume();
    }//GEN-LAST:event_idClientesKeyTyped

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
                char c= evt.getKeyChar();
        if((c<'a'||c>'z') && c<'A' |c>'Z')evt.consume();
    }//GEN-LAST:event_NombreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField RFC;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgragar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cbtipo;
    private javax.swing.JTextField codigoPostal;
    private javax.swing.JTextField idCiudad;
    private javax.swing.JTextField idClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField limiteCredito;
    private javax.swing.JTextField rSocial;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField telefono;
    // End of variables declaration//GEN-END:variables
}
