package Interfaces;

import Clases.Metodos_1;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Antonio Cervantes
 */
public class Cultivos extends javax.swing.JFrame {
Metodos_1 con;

    /**
     * Creates new form Cultivos
     */
    public Cultivos() {
        initComponents();
        
       con = new Metodos_1();
       con.abreConexion();
    }
          public void borrarTabla() {
        try {
            DefaultTableModel tabT = (DefaultTableModel) tblCultivos.getModel();
            for (int i = tabT.getRowCount() - 1; i > -1; i--) {
                tabT.removeRow(i);
            }
        } catch (Exception e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        IdCultivo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombreCultivo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        costoAsesoria = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        estatus = new javax.swing.JTextField();
        btnCancelarC = new javax.swing.JButton();
        btnAgregarC = new javax.swing.JButton();
        btnConsultarC = new javax.swing.JButton();
        btnActualizarC = new javax.swing.JButton();
        btnEliminarC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCultivos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("IdCultivo ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, 20));

        IdCultivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdCultivoKeyTyped(evt);
            }
        });
        getContentPane().add(IdCultivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 110, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Nombre ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 70, 20));

        nombreCultivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreCultivoKeyTyped(evt);
            }
        });
        getContentPane().add(nombreCultivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 200, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("CostoAsesoria");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 100, 30));
        getContentPane().add(costoAsesoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 90, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Estatus ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 60, 20));
        getContentPane().add(estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 90, 30));

        btnCancelarC.setBackground(new java.awt.Color(0, 204, 255));
        btnCancelarC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancelarC.setText("Cancelar ");
        btnCancelarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 100, 40));

        btnAgregarC.setBackground(new java.awt.Color(0, 204, 255));
        btnAgregarC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarC.setText("Agregar ");
        btnAgregarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 100, 40));

        btnConsultarC.setBackground(new java.awt.Color(0, 204, 255));
        btnConsultarC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarC.setText("Consultar ");
        btnConsultarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarCActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 110, 40));

        btnActualizarC.setBackground(new java.awt.Color(0, 204, 255));
        btnActualizarC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnActualizarC.setText("Actualizar");
        btnActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarCActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 100, 40));

        btnEliminarC.setBackground(new java.awt.Color(0, 204, 255));
        btnEliminarC.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarC.setText("Eliminar ");
        btnEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, 100, 40));

        tblCultivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IdCultivo ", "Nombre ", "CostoAsesoria", "Estatus"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCultivos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 590, 100));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel6.setText("Cultivos ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 230, 70));

        btnSalir.setBackground(new java.awt.Color(0, 204, 255));
        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 40, 80, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        Menu menu= new Menu();
        menu.setVisible(true);
        menu.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAgregarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCActionPerformed
  try{
                Object datos[]={
                    Integer.parseInt(IdCultivo.getText()),
                    nombreCultivo.getText(),
                    Float.parseFloat(costoAsesoria.getText()),
                    estatus.getText(),
                   
                };
                con.insertaCultivo(datos);
                IdCultivo.setText("");
                nombreCultivo.setText("");
                costoAsesoria.setText("");
                estatus.setText("");
            }catch(Exception e){
                IdCultivo.setText("");
                nombreCultivo.setText("");
                costoAsesoria.setText("");
                estatus.setText("");
            }
                           
         
    }//GEN-LAST:event_btnAgregarCActionPerformed

    private void btnConsultarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarCActionPerformed
        try {
            borrarTabla();
            con.consultaCultivos(tblCultivos);
        } catch (Exception e) {
            System.out.println("No hay registros"+ e);
        }
    }//GEN-LAST:event_btnConsultarCActionPerformed

    private void btnActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCActionPerformed
Object datos [] = new Object[11];
            datos[0]=Integer.parseInt(IdCultivo.getText());
            datos[1]=nombreCultivo.getText();
           datos[2]=Float.parseFloat(costoAsesoria.getText());
            datos[3]=estatus.getText();
           

            con.actualizaCultivo(datos);
            
            IdCultivo.setText("");
            nombreCultivo.setText("");
            costoAsesoria.setText("");
            estatus.setText("");
    }//GEN-LAST:event_btnActualizarCActionPerformed

    private void btnEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCActionPerformed
      int row= tblCultivos.getSelectedRow();
        int opt=JOptionPane.showConfirmDialog(this,"estas seguro que desea eliminar este registro","Pregunta",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(opt==JOptionPane.YES_OPTION){
           
         
            try {
                con.EliminarCultivo(Integer.parseInt(IdCultivo.getText()));
            } catch (SQLException ex) {
                Logger.getLogger(Clientes.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                
              
        }else{JOptionPane.showMessageDialog(null, "no ha sido eliminado");}
    }//GEN-LAST:event_btnEliminarCActionPerformed

    private void IdCultivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdCultivoKeyTyped
        char c= evt.getKeyChar();
        if(c<'a'||c>'z')evt.consume();
    }//GEN-LAST:event_IdCultivoKeyTyped

    private void nombreCultivoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreCultivoKeyTyped
                char c= evt.getKeyChar();
        if((c<'a'||c>'z') && c<'A' |c>'Z')evt.consume();
    }//GEN-LAST:event_nombreCultivoKeyTyped

    private void btnCancelarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCActionPerformed
       IdCultivo.setText("");
            nombreCultivo.setText("");
            costoAsesoria.setText("");
            estatus.setText("");
    }//GEN-LAST:event_btnCancelarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cultivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cultivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cultivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cultivos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cultivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IdCultivo;
    private javax.swing.JButton btnActualizarC;
    private javax.swing.JButton btnAgregarC;
    private javax.swing.JButton btnCancelarC;
    private javax.swing.JButton btnConsultarC;
    private javax.swing.JButton btnEliminarC;
    private javax.swing.JButton btnSalir;
    private javax.swing.JTextField costoAsesoria;
    private javax.swing.JTextField estatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreCultivo;
    private javax.swing.JTable tblCultivos;
    // End of variables declaration//GEN-END:variables
}
