package Interfaces;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Antonio Cervantes
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCliente = new javax.swing.JButton();
        btnUnidadTransporte = new javax.swing.JButton();
        btnCobros = new javax.swing.JButton();
        btnFacturas = new javax.swing.JButton();
        btnTripulacion = new javax.swing.JButton();
        btnVisitas1 = new javax.swing.JButton();
        btnVentaDetalles = new javax.swing.JButton();
        btnAsociaciones = new javax.swing.JButton();
        btnMiembros = new javax.swing.JButton();
        btnCultivos = new javax.swing.JButton();
        btnClienteCultivo = new javax.swing.JButton();
        btnOfertaAsociacion = new javax.swing.JButton();
        btnEnvios = new javax.swing.JButton();
        btnMantenimiento = new javax.swing.JButton();
        btnOfertas = new javax.swing.JButton();
        btnVentas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCliente.setBackground(new java.awt.Color(51, 204, 255));
        btnCliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCliente.setForeground(new java.awt.Color(51, 51, 51));
        btnCliente.setText("Clientes ");
        btnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 40));

        btnUnidadTransporte.setBackground(new java.awt.Color(51, 204, 255));
        btnUnidadTransporte.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUnidadTransporte.setForeground(new java.awt.Color(51, 51, 51));
        btnUnidadTransporte.setText("Unidades de transporte ");
        btnUnidadTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnidadTransporteActionPerformed(evt);
            }
        });
        getContentPane().add(btnUnidadTransporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, -1, 40));

        btnCobros.setBackground(new java.awt.Color(51, 204, 255));
        btnCobros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCobros.setForeground(new java.awt.Color(51, 51, 51));
        btnCobros.setText("Cobros");
        getContentPane().add(btnCobros, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 100, 40));

        btnFacturas.setBackground(new java.awt.Color(51, 204, 255));
        btnFacturas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFacturas.setForeground(new java.awt.Color(51, 51, 51));
        btnFacturas.setText("Facturas ");
        getContentPane().add(btnFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 100, 40));

        btnTripulacion.setBackground(new java.awt.Color(51, 204, 255));
        btnTripulacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTripulacion.setForeground(new java.awt.Color(51, 51, 51));
        btnTripulacion.setText("Tripulación");
        getContentPane().add(btnTripulacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, 110, 40));

        btnVisitas1.setBackground(new java.awt.Color(51, 204, 255));
        btnVisitas1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVisitas1.setForeground(new java.awt.Color(51, 51, 51));
        btnVisitas1.setText("Visitas ");
        getContentPane().add(btnVisitas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 100, 40));

        btnVentaDetalles.setBackground(new java.awt.Color(51, 204, 255));
        btnVentaDetalles.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVentaDetalles.setForeground(new java.awt.Color(51, 51, 51));
        btnVentaDetalles.setText("VentasDetalle");
        getContentPane().add(btnVentaDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 140, 40));

        btnAsociaciones.setBackground(new java.awt.Color(51, 204, 255));
        btnAsociaciones.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAsociaciones.setForeground(new java.awt.Color(51, 51, 51));
        btnAsociaciones.setText("Asociaciones ");
        btnAsociaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsociacionesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsociaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 140, 40));

        btnMiembros.setBackground(new java.awt.Color(51, 204, 255));
        btnMiembros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMiembros.setForeground(new java.awt.Color(51, 51, 51));
        btnMiembros.setText("Miembros");
        getContentPane().add(btnMiembros, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 140, 40));

        btnCultivos.setBackground(new java.awt.Color(51, 204, 255));
        btnCultivos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCultivos.setForeground(new java.awt.Color(51, 51, 51));
        btnCultivos.setText("Cultivos ");
        btnCultivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCultivosActionPerformed(evt);
            }
        });
        getContentPane().add(btnCultivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 140, 40));

        btnClienteCultivo.setBackground(new java.awt.Color(51, 204, 255));
        btnClienteCultivo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnClienteCultivo.setForeground(new java.awt.Color(51, 51, 51));
        btnClienteCultivo.setText("ClientesCultivo");
        getContentPane().add(btnClienteCultivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 140, 40));

        btnOfertaAsociacion.setBackground(new java.awt.Color(51, 204, 255));
        btnOfertaAsociacion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOfertaAsociacion.setForeground(new java.awt.Color(51, 51, 51));
        btnOfertaAsociacion.setText("OfertasAsociasión ");
        getContentPane().add(btnOfertaAsociacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, 40));

        btnEnvios.setBackground(new java.awt.Color(51, 204, 255));
        btnEnvios.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEnvios.setForeground(new java.awt.Color(51, 51, 51));
        btnEnvios.setText("Envios ");
        getContentPane().add(btnEnvios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 90, 40));

        btnMantenimiento.setBackground(new java.awt.Color(51, 204, 255));
        btnMantenimiento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMantenimiento.setForeground(new java.awt.Color(51, 51, 51));
        btnMantenimiento.setText("Mantenimiento ");
        getContentPane().add(btnMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, 40));

        btnOfertas.setBackground(new java.awt.Color(51, 204, 255));
        btnOfertas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOfertas.setForeground(new java.awt.Color(51, 51, 51));
        btnOfertas.setText("Ofertas ");
        getContentPane().add(btnOfertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, 40));

        btnVentas.setBackground(new java.awt.Color(51, 204, 255));
        btnVentas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVentas.setForeground(new java.awt.Color(51, 51, 51));
        btnVentas.setText("Ventas ");
        getContentPane().add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 390, 110, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Clientes.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 70, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/envio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 70, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cobros.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 70, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/factura.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, -1, 60));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/VISITAS.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 20, 70, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/detalleventas.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 70, 60));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/asosiaciones.jpg"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 70, 60));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/miembros.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 70, 60));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cultivos.jpg"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 70, 60));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clientesCultivo.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 170, 70, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/OfertasAsosiacion.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 70, 60));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/envio.jpg"))); // NOI18N
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 70, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/mantenimiento.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 70, 60));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ofertas.png"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 70, 60));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ventas.jpg"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 330, 70, 60));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chofer.png"))); // NOI18N
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, 50));

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Cerrar Seccion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, -1, 30));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUnidadTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnidadTransporteActionPerformed
UnidadesTransporte UT= new UnidadesTransporte();
UT.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnUnidadTransporteActionPerformed

    private void btnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteActionPerformed
Clientes cli= new Clientes();
cli.setVisible(true);
this.dispose();
    }//GEN-LAST:event_btnClienteActionPerformed

    private void btnAsociacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsociacionesActionPerformed
    Asociaciones aso= new Asociaciones();
      aso.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnAsociacionesActionPerformed

    private void btnCultivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCultivosActionPerformed
      Cultivos cul= new Cultivos();
      cul.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_btnCultivosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      LOGIN lo= new LOGIN();
      lo.setVisible(true);
      this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsociaciones;
    private javax.swing.JButton btnCliente;
    private javax.swing.JButton btnClienteCultivo;
    private javax.swing.JButton btnCobros;
    private javax.swing.JButton btnCultivos;
    private javax.swing.JButton btnEnvios;
    private javax.swing.JButton btnFacturas;
    private javax.swing.JButton btnMantenimiento;
    private javax.swing.JButton btnMiembros;
    private javax.swing.JButton btnOfertaAsociacion;
    private javax.swing.JButton btnOfertas;
    private javax.swing.JButton btnTripulacion;
    private javax.swing.JButton btnUnidadTransporte;
    private javax.swing.JButton btnVentaDetalles;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton btnVisitas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
